name: Build and Deploy

on: 
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    environment: ${{inputs.environment}}
 
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        if: ${{ vars.DO_WHITELIST_GITHUB_ACTION_IP == 'true' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_EC2_REGION }}

      - name: Get Runner IP Address
        id: ip
        if: ${{ vars.DO_WHITELIST_GITHUB_ACTION_IP == 'true' }}
        uses: haythem/public-ip@v1.2
      
      - name: Whitelist Runner IP Address
        if: ${{ vars.DO_WHITELIST_GITHUB_ACTION_IP == 'true' }}
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ vars.AWS_EC2_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Setup PHP
        uses: php-actions/composer@v6
        with:
          php_version: "7.4"
          php_extensions: gd zip pdo_mysql
          command: config
          args: --no-plugins allow-plugins.roots/wordpress-core-installer true

      - name: Composer config
        uses: php-actions/composer@v6
        with:
          command: config
          args: --no-plugins allow-plugins.composer/installers true

      - name: Composer validate
        uses: php-actions/composer@v6
        with:
          command: validate

      - name: Composer install
        uses: php-actions/composer@v6

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          TARGET: ${{ vars.REMOTE_BASE }}/deploy-cache
          EXCLUDE: ".git*, /web/app/uploads"

      - name: Post-deployment script
        uses: appleboy/ssh-action@v0.1.10
        env:
          COMMIT_HASH: ${{ github.sha }}
          TARGET_DIR: ${{ vars.REMOTE_BASE }}
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ vars.REMOTE_USER }}
          envs: COMMIT_HASH,TARGET_DIR
          script: |
            cd ${TARGET_DIR}
            find deploy-cache -not -perm -g=w -exec chmod -R g+w {} \;
            if [ ! -d "releases/${COMMIT_HASH}" ]
            then
            echo "Creating: releases/${COMMIT_HASH}"
            cp -dR deploy-cache releases/${COMMIT_HASH}
            fi
            echo "Linking current to revision: ${COMMIT_HASH}"
            rm -f current
            ln -s releases/${COMMIT_HASH} current
            echo "Removing old releases"
            # cd releases && ls -1t | tail -n +11 | xargs rm -rf
            # find . -not -perm -g=w -exec chmod -R g+w {} \;

      - name: Revoke Runner IP address
        if: ${{ vars.DO_WHITELIST_GITHUB_ACTION_IP == 'true' }}
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ vars.AWS_EC2_SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
